version: 2

build:
   os: ubuntu-22.04
   jobs:
      pre_build:
         - python -m sphinx -W -b spelling docs/ _build/spelling
         - python -m sphinx -W -b linkcheck docs/ _build/linkcheck
   tools:
      python: "3.10"

sphinx:
   configuration: docs/conf.py
   fail_on_warning: true

python:
   install:
     - method: pip
       path: .
       extra_requirements:
         - docs
